-- 1 
SELECT NOME FROM CATEGORIA WHERE VALOR_DIA BETWEEN 100 AND 200;

-- 2
SELECT NOME FROM CATEGORIA WHERE NOME ILIKE '%LUXO%';

-- 3
SELECT NOME FROM CATEGORIA C 
JOIN APARTAMENTO A 
ON C.COD_CAT = A.COD_CAT 
JOIN HOSPEDAGEM H 
ON A.NUM = H.NUM
WHERE DT_ENT <= NOW() - INTERVAL '5 YEARS';

-- 4
SELECT A.NUM FROM APARTAMENTO A 
JOIN HOSPEDAGEM H2
ON A.NUM = H2.NUM
WHERE DT_SAI IS NULL;

-- 5
SELECT NUM FROM APARTAMENTO WHERE COD_CAT IN (1, 2, 3, 11, 34, 54, 24, 12);

-- 6
SELECT NUM FROM APARTAMENTO A 
JOIN CATEGORIA C
ON A.COD_CAT = C.COD_CAT
WHERE NOME ILIKE 'LUXO%';

-- 7 
SELECT COUNT(NUM) FROM APARTAMENTO;

-- 8 
SELECT SUM(VALOR_DIA) FROM CATEGORIA;

-- 9
SELECT AVG(VALOR_DIA) FROM CATEGORIA;

-- 10
SELECT MAX(VALOR_DIA) FROM CATEGORIA;

-- 11
SELECT MIN(VALOR_DIA) FROM CATEGORIA;

-- 12
SELECT AVG(VALOR_DIA), H.NOME
FROM CATEGORIA C 
JOIN APARTAMENTO A
ON C.COD_CAT = A.COD_CAT
JOIN HOSPEDAGEM H2
ON A.NUM = H2.NUM
JOIN HOSPEDE H
ON H2.COD_HOSP = H.COD_HOSP
GROUP BY H.COD_HOSP;

-- 13
SELECT NOME, COALESCE(COUNT(A.NUM), 0) AS QUANTIDADE_APS
FROM CATEGORIA C
LEFT JOIN APARTAMENTO A ON C.COD_CAT = A.COD_CAT
GROUP BY C.NOME;

-- 14
SELECT NOME
FROM CATEGORIA
NATURAL JOIN APARTAMENTO
GROUP BY NOME
HAVING COUNT(*) > 1;

-- 15
SELECT NOME FROM HOSPEDE WHERE DT_NASC > '1970-01-01';

-- 16
SELECT COUNT(*) FROM HOSPEDE;

-- 17
SELECT A.NUM, COUNT(*) AS quantidade_hospedagens
FROM APARTAMENTO A
NATURAL JOIN HOSPEDAGEM H
GROUP BY A.NUM
HAVING COUNT(*) > 1;

-- 18
ALTER TABLE HOSPEDE
ADD COLUMN NACIONALIDADE VARCHAR(30);

-- 19
SELECT COUNT(*), NACIONALIDADE FROM HOSPEDE GROUP BY NACIONALIDADE;

-- 20
SELECT NOME, DT_NASC FROM HOSPEDE WHERE DT_NASC IN (SELECT MIN(DT_NASC) FROM HOSPEDE);

ou  

SELECT NOME, DT_NASC 
FROM HOSPEDE 
ORDER BY DT_NASC ASC 
LIMIT 1;

-- 21
SELECT NOME, DT_NASC FROM HOSPEDE WHERE DT_NASC IN (SELECT MAX(DT_NASC) FROM HOSPEDE);

-- 22
UPDATE CATEGORIA 
SET VALOR_DIA = VALOR_DIA + (VALOR_DIA * 0.10);

-- 23
SELECT NOME
FROM CATEGORIA C
LEFT JOIN APARTAMENTO A 
ON C.COD_CAT = A.COD_CAT
WHERE NUM IS NULL;

-- 24
SELECT A.NUM FROM APARTAMENTO A
LEFT JOIN HOSPEDAGEM H2
ON A.NUM = H2.NUM
WHERE H2.NUM IS NULL;

-- 25
SELECT MAX(VALOR_DIA) FROM CATEGORIA C
JOIN APARTAMENTO A
ON C.COD_CAT = A.COD_CAT
JOIN HOSPEDAGEM H2
ON A.NUM = H2.NUM
JOIN HOSPEDE H
ON H2.COD_HOSP = H.COD_HOSP
WHERE H.NOME ILIKE 'JOÃO%';

-- 26
SELECT DISTINCT NOME FROM HOSPEDE H  
LEFT JOIN HOSPEDAGEM H2  
ON H.COD_HOSP = H2.COD_HOSP
WHERE NUM <> 201;

-- 27
SELECT NOME FROM HOSPEDE WHERE COD_HOSP NOT IN 
(SELECT COD_HOSP FROM HOSPEDAGEM NATURAL JOIN APARTAMENTO
NATURAL JOIN CATEGORIA WHERE NOME ILIKE 'LUXO');

-- 28
SELECT DISTINCT H.NOME
FROM HOSPEDE H
JOIN (
  SELECT H2.COD_HOSP, H2.NUM FROM HOSPEDAGEM H2 
  UNION 
  SELECT R.COD_HOSP, R.NUM FROM RESERVA R
) AS HOSP_RES ON H.COD_HOSP = HOSP_RES.COD_HOSP
JOIN APARTAMENTO A ON A.NUM = HOSP_RES.NUM
JOIN CATEGORIA C ON C.COD_CAT = A.COD_CAT
WHERE C.NOME ILIKE 'LUXO';

-- 29
SELECT DISTINCT H.NOME FROM HOSPEDE H NATURAL JOIN HOSPEDAGEM
NATURAL JOIN APARTAMENTO AP JOIN CATEGORIA CA 
ON AP.COD_CAT=CA.COD_CAT
WHERE CA.NOME ILIKE 'LUXO' AND 
COD_HOSP NOT IN (SELECT COD_HOSP FROM RESERVA NATURAL JOIN
                                APARTAMENTO NATURAL JOIN CATEGORIA WHERE
                                NOME ILIKE 'LUXO');

-- 30

SELECT DISTINCT H.NOME FROM HOSPEDE H NATURAL JOIN HOSPEDAGEM
NATURAL JOIN APARTAMENTO AP JOIN CATEGORIA CA 
ON AP.COD_CAT=CA.COD_CAT
WHERE CA.NOME ILIKE 'LUXO' AND 
COD_HOSP IN (SELECT COD_HOSP FROM RESERVA NATURAL JOIN
                                APARTAMENTO NATURAL JOIN CATEGORIA WHERE
                                NOME ILIKE 'LUXO');