'Exercício:
 Crie a tabela venda com os seguintes atributos:
 Cod_venda
 Nome_vendedor
 data_venda
 Valor_vendido
 1) Povoe a tabela com 10 vendas, considerando que existam apenas 4
vendedores na loja.
 2.1) Mostre o nome dos vendedores que venderam mais de X reais no
mês de março de 2024.
 2.2) Mostre o nome de um dos vendedores que mais vendeu no mês
de março de 2024
 3) Sem usar “select na cláusula from,”qual o nome do(s)
vendedor(es) que mais vendeu no mês de março de 2024?'

CREATE TABLE VENDA(
	COD_VENDA SERIAL PRIMARY KEY,
	NOME_VENDEDOR VARCHAR(30) NOT NULL,
	DATA_VENDA DATE NOT NULL,
	VALOR_VENDIDO FLOAT NOT NULL
)

INSERT INTO VENDA (NOME_VENDEDOR, DATA_VENDA, VALOR_VENDIDO) VALUES('CARLOS', '2024-04-22', 55.60)
INSERT INTO VENDA (NOME_VENDEDOR, DATA_VENDA, VALOR_VENDIDO) VALUES('MATEUS', '2024-05-15', 60.00)
INSERT INTO VENDA (NOME_VENDEDOR, DATA_VENDA, VALOR_VENDIDO) VALUES('LUIZA', '2024-01-03', 43.20)
INSERT INTO VENDA (NOME_VENDEDOR, DATA_VENDA, VALOR_VENDIDO) VALUES('MARCOS', '2024-02-21', 12.00)
INSERT INTO VENDA (NOME_VENDEDOR, DATA_VENDA, VALOR_VENDIDO) VALUES ('CARLOS', '2024-05-10', 75.50)
INSERT INTO VENDA (NOME_VENDEDOR, DATA_VENDA, VALOR_VENDIDO) VALUES ('MATEUS', '2024-03-18', 89.30)
INSERT INTO VENDA (NOME_VENDEDOR, DATA_VENDA, VALOR_VENDIDO) VALUES ('LUIZA', '2024-06-07', 33.80)
INSERT INTO VENDA (NOME_VENDEDOR, DATA_VENDA, VALOR_VENDIDO) VALUES ('MARCOS', '2024-04-30', 22.50)
INSERT INTO VENDA (NOME_VENDEDOR, DATA_VENDA, VALOR_VENDIDO) VALUES ('CARLOS', '2024-02-14', 45.70)
INSERT INTO VENDA (NOME_VENDEDOR, DATA_VENDA, VALOR_VENDIDO) VALUES ('LUIZA', '2024-03-22', 52.40)

SELECT * FROM VENDA

SELECT NOME_VENDEDOR, VALOR_VENDIDO
FROM VENDA
WHERE DATA_VENDA BETWEEN '2024-03-01' AND '2024-03-31'
AND VALOR_VENDIDO > 25

SELECT NOME_VENDEDOR
FROM VENDA
WHERE DATA_VENDA BETWEEN '2024-03-01' AND '2024-03-31'
AND VALOR_VENDIDO = (SELECT MAX(VALOR_VENDIDO) FROM VENDA)

CREATE VIEW MELHOR_VENDEDOR
AS SELECT NOME_VENDEDOR
FROM VENDA
WHERE DATA_VENDA BETWEEN '2024-03-01' AND '2024-03-31'
AND VALOR_VENDIDO = (SELECT MAX(VALOR_VENDIDO) FROM VENDA)

SELECT * FROM MELHOR_VENDEDOR